Starting time is Fri  9 Dec 2022 17:20:13 CET
Blender PIP user site: /Users/ole/.local/lib/python3.10/site-packages
Adding site to path
HG_INFO:	[0m Activating HumGen, version (4, 0, 1)
============================= test session starts ==============================
platform darwin -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/ole/Documents/HumGen3D
plugins: cov-4.0.0, lazy-fixture-0.6.3
collected 9 items

tests/human/test_body.py .E..E..E.                                       [100%]

==================================== ERRORS ====================================
___________ ERROR at setup of test_randomize_body[male_rigify_human] ___________

request = <FixtureRequest for <Function test_randomize_body[male_rigify_human]>>

    def fill(request):
        item = request._pyfuncitem
        fixturenames = getattr(item, "fixturenames", None)
        if fixturenames is None:
            fixturenames = request.fixturenames
    
        if hasattr(item, 'callspec'):
            for param, val in sorted_by_dependency(item.callspec.params, fixturenames):
                if val is not None and is_lazy_fixture(val):
>                   item.callspec.params[param] = request.getfixturevalue(val.name)

../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/python/lib/python3.10/site-packages/pytest_lazyfixture.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/tests/fixtures.py:52: in male_rigify_human
    human.pose.rigify.generate(bpy.context)
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/common/decorators.py:56: in wrapper
    return func(*args, **kwargs)
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/pose/rigify.py:38: in generate
    rigify.generate.generate_rig(context, human.objects.rig)
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:617: in generate_rig
    raise e
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:605: in generate_rig
    generator.generate()
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:414: in generate
    self.obj = obj = self.ensure_rig_object()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rigify.generate.Generator object at 0x15fba2590>

    def ensure_rig_object(self) -> bpy.types.Object:
        """Check if the generated rig already exists, so we can
        regenerate in the same object. If not, create a new
        object to generate the rig in.
        """
        print("Fetch rig.")
        meta_data = self.metarig.data
    
>       target_rig = meta_data.rigify_target_rig
E       AttributeError: 'Armature' object has no attribute 'rigify_target_rig'

../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:66: AttributeError
---------------------------- Captured stdout setup -----------------------------
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
Fetch rig.
Rigify: failed to generate rig.
_____________ ERROR at setup of test_reset_body[male_rigify_human] _____________

request = <FixtureRequest for <Function test_reset_body[male_rigify_human]>>

    def fill(request):
        item = request._pyfuncitem
        fixturenames = getattr(item, "fixturenames", None)
        if fixturenames is None:
            fixturenames = request.fixturenames
    
        if hasattr(item, 'callspec'):
            for param, val in sorted_by_dependency(item.callspec.params, fixturenames):
                if val is not None and is_lazy_fixture(val):
>                   item.callspec.params[param] = request.getfixturevalue(val.name)

../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/python/lib/python3.10/site-packages/pytest_lazyfixture.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/tests/fixtures.py:52: in male_rigify_human
    human.pose.rigify.generate(bpy.context)
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/common/decorators.py:56: in wrapper
    return func(*args, **kwargs)
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/pose/rigify.py:38: in generate
    rigify.generate.generate_rig(context, human.objects.rig)
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:617: in generate_rig
    raise e
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:605: in generate_rig
    generator.generate()
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:414: in generate
    self.obj = obj = self.ensure_rig_object()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rigify.generate.Generator object at 0x16044b640>

    def ensure_rig_object(self) -> bpy.types.Object:
        """Check if the generated rig already exists, so we can
        regenerate in the same object. If not, create a new
        object to generate the rig in.
        """
        print("Fetch rig.")
        meta_data = self.metarig.data
    
>       target_rig = meta_data.rigify_target_rig
E       AttributeError: 'Armature' object has no attribute 'rigify_target_rig'

../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:66: AttributeError
---------------------------- Captured stdout setup -----------------------------
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
Fetch rig.
Rigify: failed to generate rig.
_____________ ERROR at setup of test_body_keys[male_rigify_human] ______________

request = <FixtureRequest for <Function test_body_keys[male_rigify_human]>>

    def fill(request):
        item = request._pyfuncitem
        fixturenames = getattr(item, "fixturenames", None)
        if fixturenames is None:
            fixturenames = request.fixturenames
    
        if hasattr(item, 'callspec'):
            for param, val in sorted_by_dependency(item.callspec.params, fixturenames):
                if val is not None and is_lazy_fixture(val):
>                   item.callspec.params[param] = request.getfixturevalue(val.name)

../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/python/lib/python3.10/site-packages/pytest_lazyfixture.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/tests/fixtures.py:52: in male_rigify_human
    human.pose.rigify.generate(bpy.context)
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/common/decorators.pyBlender 3.4.0 (hash a95bf1ac01be built 2022-12-07 00:47:22)
Read prefs: /Users/ole/Library/Application Support/Blender/3.4/config/userpref.blend
:56: in wrapper
    return func(*args, **kwargs)
../../Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/pose/rigify.py:38: in generate
    rigify.generate.generate_rig(context, human.objects.rig)
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:617: in generate_rig
    raise e
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:605: in generate_rig
    generator.generate()
../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:414: in generate
    self.obj = obj = self.ensure_rig_object()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <rigify.generate.Generator object at 0x16047ff40>

    def ensure_rig_object(self) -> bpy.types.Object:
        """Check if the generated rig already exists, so we can
        regenerate in the same object. If not, create a new
        object to generate the rig in.
        """
        print("Fetch rig.")
        meta_data = self.metarig.data
    
>       target_rig = meta_data.rigify_target_rig
E       AttributeError: 'Armature' object has no attribute 'rigify_target_rig'

../../blender_executables/blender-3.4.0-macos-x64/Contents/Resources/3.4/scripts/addons/rigify/generate.py:66: AttributeError
---------------------------- Captured stdout setup -----------------------------
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
HG_INFO:	[0m <FrameSummary file /Users/ole/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/human/human.py, line 220 in from_preset>
[93mHG_WARNING:	[0m Argument 'context' for function 'set_from_dict' substituted with bpy.context.  It's highly recommended to pass your own context!
Fetch rig.
Rigify: failed to generate rig.
=========================== short test summary info ============================
ERROR tests/human/test_body.py::test_randomize_body[male_rigify_human] - Attr...
ERROR tests/human/test_body.py::test_reset_body[male_rigify_human] - Attribut...
ERROR tests/human/test_body.py::test_body_keys[male_rigify_human] - Attribute...
========================= 6 passed, 3 errors in 56.42s =========================
